server:
  port: 8081
spring:
  application:
    name: dubbo-provider
dubbo:
  scan:
    base-packages: com.lk.aggregation.impl
  consumer:
    check: false
  application:
    id: dubbo-provider
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
    check: false
    id: dubbo-demo-test